version: "2.2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - webnet
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - webnet
    volumes:
      - /var/lib/postgres/docker/rabbit-clone:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: rebbit2
  # web:
  #   image: rabbit-clone-server
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - webnet
  #   environment:
  #     DB_HOST: db
  #     REDIS_HOST: redis
networks:
  webnet:
# volumes:
  # db-data: /var/lib/postgres/:/var/lib/postgresql/data
